import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import statsRouter from "./stats";
import categoriesRouter from "./categories";
import locationsRouter from "./locations";
import businessesRouter from "./businesses";
import reviewsRouter from "./reviews";
import agentsRouter from "./agents";
import adminRouter from "./admin";
import streetExplorerRouter from "./streetexplorer";
import claimsRouter from "./claims";
import geoRouter from "./geo";
import contactRouter from "./contact";
import supportTicketsRouter from "./support-tickets";
import ridersRouter from "./riders";
import deliveriesRouter, { standaloneDeliveriesRouter, businessMarketRouter } from "./deliveries";
import marketplaceItemsRouter, { standaloneMarketplaceItemsRouter } from "./marketplace-items";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/stats", statsRouter);
router.use("/geo", geoRouter);
router.use("/categories", categoriesRouter);
router.use(locationsRouter);
router.use("/businesses", businessesRouter);
router.use("/businesses/:businessId/reviews", reviewsRouter);
router.use("/businesses/:businessId/claim", claimsRouter);
router.use("/businesses/:businessId/deliveries", deliveriesRouter);
router.use("/businesses/:businessId/marketplace-items", marketplaceItemsRouter);
router.use("/businesses/:businessId", businessMarketRouter);
router.use("/marketplace-items", standaloneMarketplaceItemsRouter);
router.use("/agents", agentsRouter);
router.use("/riders", ridersRouter);
router.use("/deliveries", standaloneDeliveriesRouter);
router.use("/admin", adminRouter);
router.use("/streets", streetExplorerRouter);
router.use("/contact", contactRouter);
router.use("/support-tickets", supportTicketsRouter);

export default router;
