import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import statsRouter from "./stats";
import categoriesRouter from "./categories";
import locationsRouter from "./locations";
import businessesRouter from "./businesses";
import reviewsRouter from "./reviews";
import agentsRouter from "./agents";
import adminRouter from "./admin";
import streetExplorerRouter from "./streetexplorer";
import claimsRouter from "./claims";
import geoRouter from "./geo";
import contactRouter from "./contact";
import supportTicketsRouter from "./support-tickets";
import ridersRouter from "./riders";
import deliveriesRouter, { standaloneDeliveriesRouter, businessMarketRouter } from "./deliveries";
import marketplaceItemsRouter, { standaloneMarketplaceItemsRouter } from "./marketplace-items";
import storageRouter from "./storage";
import analyticsRouter from "./analytics";
import referralsRouter from "./referrals";
import chatRouter from "./chat";
import propertiesRouter from "./properties";
import regionalManagerRouter from "./regional-manager";
import publicRouter from "./public";
import pushRouter from "./push";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use(publicRouter);
router.use("/auth", authRouter);
router.use("/stats", statsRouter);
router.use("/geo", geoRouter);
router.use("/categories", categoriesRouter);
router.use(locationsRouter);
router.use("/businesses", businessesRouter);
router.use("/businesses/:businessId/reviews", reviewsRouter);
router.use("/businesses/:businessId/claim", claimsRouter);
router.use("/businesses/:businessId/deliveries", deliveriesRouter);
router.use("/businesses/:businessId/marketplace-items", marketplaceItemsRouter);
router.use("/businesses/:businessId/analytics", analyticsRouter);
router.use("/businesses/:businessId", businessMarketRouter);
router.use("/marketplace-items", standaloneMarketplaceItemsRouter);
router.use("/agents", agentsRouter);
router.use("/riders", ridersRouter);
router.use("/deliveries", standaloneDeliveriesRouter);
router.use("/admin", adminRouter);
router.use("/streets", streetExplorerRouter);
router.use("/contact", contactRouter);
router.use("/support-tickets", supportTicketsRouter);
router.use("/analytics", analyticsRouter);
router.use("/users", referralsRouter);
router.use("/conversations", chatRouter);
router.use("/properties", propertiesRouter);
router.use("/regional-manager", regionalManagerRouter);
router.use("/push", pushRouter);

export default router;
