// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/map-enhancements/ClusteredMarkers.tsx": () => import("../components/mockups/map-enhancements/ClusteredMarkers.tsx"),
  "./components/mockups/map-enhancements/DarkHeatLayer.tsx": () => import("../components/mockups/map-enhancements/DarkHeatLayer.tsx"),
  "./components/mockups/map-enhancements/GlassHUD.tsx": () => import("../components/mockups/map-enhancements/GlassHUD.tsx")
};
